#
# Формат расписания
#  N - отключено (цифра ноль)
#  d - ежедневно
#  w - еженедельно (по-умолчанию, по понедельникам)
#  w[1,2,3,4,5,6,7] - еженедельно, в указаные дни недели
#  m - ежемесячно (по-умолчанию, 1 числа)
#  m[1,2,..,31] - ежемесячно, в указаные числа

storage: /mnt/backup/
exclude:
#  - /var/log/nginx

schedule:
  monthly:
    - system
  weekly:
    - home
  daily:
    - mysql
    - postgres
  managed:
    - websites
#    - special
    - cleanup # Must always be last!

#
# Указываем сроки хранения для директорий в формате strtotime
#
# monthly - первое число месяца
# weekly  - понедельник каждой недели (кроме monthly)
# daily   - каждый день (кроме monthly и weekly)
#
cleanup:
  monthly: "1 month"
  weekly:  "4 weeks"
  daily:   "7 days"

system:
  include:
    - /etc
    - /root
    - /usr/local
    - /var/log
    - /var/spool
    - /var/www
  exclude: [ ]
  packages: Debian

home:
  exclude:
    - websites

websites:
  # no excludes are supported here
  list: /home/*/websites
  preg: "#^(/home/(.*?)/websites):#"
  period_default: "weekly"
  period_override:
    h_informatika: "monthly"
    h_druidvav_.nekoweb: "monthly"
    h_druidvav_shinkansen.ru: "monthly"
    h_otaku_wiki.otaku.ru: "monthly"

#special:
#  var_www:
#    period: monthly
#    include:
#      - /var/www
#    exclude: [ ]
  
mysql:
  hostname: localhost
  username: root
  password: jecneOcwev8
  exclude:
    - information_schema

postgres:
  sh_user: postgres
  exclude:
    - postgres

dropbox:
  key: 3i2d0m8fgzk5cdw
  secret: l3g7z1ishxosiyx

  token: ia4pd7yome0r4zs
  token_secret: x0qe4qo47cj8m1l